// 배송 가능 국가. VANAM의 실제 시장(전시·협력 지역) 위주로 추렸다.
// value 는 ISO 3166-1 alpha-2. 'OTHER' 선택 시 국가명을 직접 입력받는다.
export const COUNTRIES: { code: string; ko: string; en: string }[] = [
  { code: 'KR', ko: '대한민국', en: 'South Korea' },
  { code: 'US', ko: '미국', en: 'United States' },
  { code: 'JP', ko: '일본', en: 'Japan' },
  { code: 'CN', ko: '중국', en: 'China' },
  { code: 'TW', ko: '대만', en: 'Taiwan' },
  { code: 'HK', ko: '홍콩', en: 'Hong Kong' },
  { code: 'SG', ko: '싱가포르', en: 'Singapore' },
  { code: 'MY', ko: '말레이시아', en: 'Malaysia' },
  { code: 'TH', ko: '태국', en: 'Thailand' },
  { code: 'VN', ko: '베트남', en: 'Vietnam' },
  { code: 'IN', ko: '인도', en: 'India' },
  { code: 'ID', ko: '인도네시아', en: 'Indonesia' },
  { code: 'PH', ko: '필리핀', en: 'Philippines' },
  { code: 'AU', ko: '호주', en: 'Australia' },
  { code: 'NZ', ko: '뉴질랜드', en: 'New Zealand' },
  { code: 'DE', ko: '독일', en: 'Germany' },
  { code: 'GB', ko: '영국', en: 'United Kingdom' },
  { code: 'FR', ko: '프랑스', en: 'France' },
  { code: 'NL', ko: '네덜란드', en: 'Netherlands' },
  { code: 'BE', ko: '벨기에', en: 'Belgium' },
  { code: 'CH', ko: '스위스', en: 'Switzerland' },
  { code: 'AT', ko: '오스트리아', en: 'Austria' },
  { code: 'IT', ko: '이탈리아', en: 'Italy' },
  { code: 'ES', ko: '스페인', en: 'Spain' },
  { code: 'PT', ko: '포르투갈', en: 'Portugal' },
  { code: 'IE', ko: '아일랜드', en: 'Ireland' },
  { code: 'SE', ko: '스웨덴', en: 'Sweden' },
  { code: 'NO', ko: '노르웨이', en: 'Norway' },
  { code: 'DK', ko: '덴마크', en: 'Denmark' },
  { code: 'FI', ko: '핀란드', en: 'Finland' },
  { code: 'PL', ko: '폴란드', en: 'Poland' },
  { code: 'CZ', ko: '체코', en: 'Czechia' },
  { code: 'IL', ko: '이스라엘', en: 'Israel' },
  { code: 'AE', ko: '아랍에미리트', en: 'United Arab Emirates' },
  { code: 'SA', ko: '사우디아라비아', en: 'Saudi Arabia' },
  { code: 'TR', ko: '튀르키예', en: 'Türkiye' },
  { code: 'CA', ko: '캐나다', en: 'Canada' },
  { code: 'MX', ko: '멕시코', en: 'Mexico' },
  { code: 'BR', ko: '브라질', en: 'Brazil' },
  { code: 'OTHER', ko: '기타 (직접 입력)', en: 'Other (specify)' },
];

export const isKnownCountry = (c: string) => COUNTRIES.some((x) => x.code === c);
