// 보안 헤더 미들웨어.
//
// ⚠️ 왜 필요한가:
//   public/_headers 는 Cloudflare 가 "정적 자산" 응답에만 붙인다.
//   Worker 코드가 생성하는 SSR 응답(prerender=false)에는 _headers 가 적용되지 않는다.
//   (Cloudflare 공식 문서 명시: "Custom headers defined in the _headers file are not
//    applied to responses generated by your Worker code")
//   → /admin, /checkout, /order/* 등 SSR 페이지가 _headers 의 CSP·클릭재킹 방어를 못 받는다.
//     특히 /admin 은 클릭재킹 방어가 가장 필요한 페이지다.
//
//   그래서 이 미들웨어가 SSR 응답에 같은 보안 헤더를 직접 주입한다.
//   Astro 미들웨어는 on-demand(SSR) 렌더링에만 실행되므로,
//   정적 페이지(_headers 담당)와 SSR 페이지(미들웨어 담당)가 정확히 상보적으로 커버된다.
//
// ⚠️ HTML 응답에만 CSP 를 건다:
//   /api/* 의 JSON 응답이나 리다이렉트에 CSP 를 걸 이유는 없다(내용이 HTML 이 아니라 무의미).
//   단, 클릭재킹·MIME 스니핑 차단 헤더는 모든 SSR 응답에 붙여 둔다(부작용 없음).
//
// ⚠️ /keystatic, /api/keystatic 은 완화:
//   Keystatic Cloud React UI 가 api.keystatic.cloud·GitHub 에 접속하고 인라인 스타일·워커를 쓴다.
//   전역 CSP 로는 깨지므로 이 경로에는 CSP 를 걸지 않는다(클릭재킹·스니핑 차단은 유지).
import { defineMiddleware } from 'astro:middleware';

// 전역 CSP — public/_headers 의 /* 블록과 동일하게 유지할 것.
//   script-src 'unsafe-inline'  : 인라인 스크립트(JSON-LD·reveal·모바일메뉴). client: 0개라 nonce 불필요.
//   style-src  'unsafe-inline' + cdn.jsdelivr.net : 인라인 스타일 + 폰트 onload 핸들러 + Pretendard CSS.
//   font-src   cdn.jsdelivr.net : Pretendard.
//   connect-src 'self' : fetch 는 전부 /api/* 내부.
//   frame-ancestors 'none' : 클릭재킹 완전 차단.
const CSP =
  "default-src 'self'; " +
  "script-src 'self' 'unsafe-inline' https://challenges.cloudflare.com https://www.paypal.com https://www.sandbox.paypal.com https://www.paypalobjects.com; " +
  "style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; " +
  "font-src 'self' https://cdn.jsdelivr.net data:; " +
  "img-src 'self' data: https://www.paypalobjects.com https://www.paypal.com; " +
  "connect-src 'self' https://challenges.cloudflare.com https://www.paypal.com https://www.sandbox.paypal.com; " +
  "object-src 'none'; " +
  "frame-src https://challenges.cloudflare.com https://www.google.com https://maps.google.com https://www.linkedin.com https://www.paypal.com https://www.sandbox.paypal.com; " +
  "frame-ancestors 'none'; " +
  "base-uri 'self'; " +
  "form-action 'self'";

export const onRequest = defineMiddleware(async (context, next) => {
  const response = await next();

  const path = context.url.pathname;

  // Keystatic 관리자/ API 는 CSP 예외 (GitHub·keystatic.cloud 접속, 인라인 스타일·워커).
  const isKeystatic = path === '/keystatic' || path.startsWith('/keystatic/') || path.startsWith('/api/keystatic');

  // 모든 SSR 응답 공통: 클릭재킹·MIME 스니핑·레퍼러·권한 차단 (부작용 없음)
  response.headers.set('X-Frame-Options', 'DENY');
  response.headers.set('X-Content-Type-Options', 'nosniff');
  response.headers.set('Referrer-Policy', 'strict-origin-when-cross-origin');
  response.headers.set('Strict-Transport-Security', 'max-age=31536000; includeSubDomains; preload');

  // CSP 는 HTML 응답에만, 그리고 Keystatic 경로 제외.
  const ct = response.headers.get('Content-Type') ?? '';
  if (!isKeystatic && ct.includes('text/html')) {
    response.headers.set('Content-Security-Policy', CSP);
    response.headers.set(
      'Permissions-Policy',
      'camera=(), microphone=(), geolocation=(), interest-cohort=()',
    );
  }

  return response;
});
